name: CI

on:
    push:
        branches: [main]


jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        working-directory: server/
        run: npm install
    #   - name: Run test
    #     working-directory: server/
    #     run: npm run test